### ISSUE TITLE
Unable to sort all gradle files, but individual sorting works

### ISSUE THREAD

**Issue by JakeSteam** [j-roskopf/GradleFileSorterPlugin#13]
Hey!

Sorting files individually using context menu is working great, but I'm getting the following error when using "Format All Gradle Files" and no changes are made (despite saying "Sorting has been completed"):
```

Errors occurred on the following files: build.gradle.kts, build.gradle.kts, build.gradle.kts, build.gradle.kts, build.gradle.kts, build.gradle.kts, build.gradle.kts, build.gradle.kts, build.gradle.kts, build.gradle.kts, build.gradle.kts, build.gradle.kts, build.gradle.kts, build.gradle.kts, build.gradle.kts, build.gradle.kts, build.gradle.kts, build.gradle.kts, build.gradle.kts, build.gradle.kts, build.gradle.kts, build.gradle.kts, build.gradle.kts, build.gradle.kts, build.gradle.kts, build.gradle.kts, build.gradle.kts, build.gradle.kts, build.gradle.kts, build.gradle.kts, build.gradle.kts, build.gradle.kts
```
![image](https://github.com/user-attachments/assets/d656bee4-07cb-44f9-aa52-e4ff0c93b640)

Misc info about my setup:
* Android Studio Koala | 2024.1.1 Patch 1, using "New UI"
* MacOS 13.2
* 14 module project (despite all the `build.gradle.kts` in the error!)

I couldn't figure out a way to get any sort of debug logs for you, let me know what you need!

**Comment by j-roskopf** [comment]
Hey! tremendously sorry for the delayed response. I didn't see any notifications come through my email and I missed the issue. 

As a quick triage, it looks like I throw that error when I couldn't find the `dependencies` block within a gradle file or when a generic exception occurs.

Are you able to perchance share a sample build.gradle.kts file from your project? Absolutely no worries if not

I usually use these 3 projects as validation in the plugin:

1. https://github.com/android/nowinandroid
2. https://github.com/moezbhatti/qksms
3. https://github.com/chrisbanes/tivi

**Comment by JakeSteam** [comment]
Hey, no worries at all.

That's the thing, sorting individually works fine, but sorting all is what fails, seemingly failing on more gradle files than are even in the project! 

I'll have a play tomorrow with a blank project and get back to you, no rush to reply.

**Comment by j-roskopf** [comment]
Just kidding, I can repro the problem :) 


```
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Write access is allowed inside write-action only (see Application.runWriteAction()); see https://jb.gg/ij-platform-threading for details
Current thread: Thread[AWT-EventQueue-0,6,main] 1458562575 (EventQueue.isDispatchThread()=true)
SystemEventQueueThread: (same)
```

Will have a PR up shortly!

**Comment by j-roskopf** [comment]
Uploading 1.0.9 with the fix to intellij marketplace shortly!

**Comment by JakeSteam** [comment]
Just confirming v1.0.9 works as expected, thanks!
